% find pseudospectra of 1D waves on staggered patches using
% ideal wave systems in the form h_t=u_x+... and u_u=h_x+...
% AJR, May 2023
%!TEX root = ../Doc/eqnFreeDevMan.tex
%{
\section{\texttt{waveIdealPS}: simulate a water wave PDE on patches}
\label{sec:waveIdealPS}
%\localtableofcontents

\cref{fig:ps1WaveCtsUH} shows an example simulation in time
generated by the patch scheme applied to an ideal wave \pde\
\cite[]{Cao2013}. The inter-patch coupling is realised by
spectral interpolation of the mid-patch values to the patch
edges.


Establish the global data struct~\verb|patches| for the
\pde{}s (linearised) solved on \(2\pi\)-periodic domain,
with eight patches, each patch of half-size ratio~\(0.1\),
with seven/eleven micro-grid points within each patch, and
spectral interpolation~(\(-1\)) of `staggered' macroscale
patches to provide the edge-values of the inter-patch
coupling conditions.
\begin{matlab}
%}
global patches
nPatch = 8
ratio = 0.1
nSubP = 11 %of the form 4*n-1
Len = 2*pi;
configPatches1(@idealWavePDE,[0 Len],nan,nPatch,-1,ratio,nSubP);
%{
\end{matlab}

Identify which micro-grid points are \(h\)~or~\(u\) values
on the staggered micro-grid. Also store the information in
the struct~\verb|patches| for use by the time derivative
function.
\begin{matlab}
%}
tmp = mod( (1:nSubP)'+(1:nPatch) ,2);
patches.hPts = find(tmp==0);
patches.uPts = find(tmp==1);
%{
\end{matlab}

Form the Jacobian matrix, linear operator, by numerical
construction about a zero field.  Use~\verb|i| to store the
indices of the micro-grid points that are interior to the
patches and hence are the system variables.
\begin{matlab}
%}
  u0 = zeros(nSubP,1,1,nPatch);
  u0([1 end],:,:,:)=nan; u0=u0(:);
  i = find(~isnan(u0));
  nJac = length(i)
  Jac = nan(nJac);
  for j = 1:nJac
    u0(i) = ((1:nJac)==j);
    dudt = patchSys1(0,u0);
    Jac(:,j) = dudt(i);
  end
  Jac(abs(Jac)<1e-12) = 0;
%{
\end{matlab}
Find the eigenvalues of the Jacobian: the spectral
interpolation is effectively exact for the macroscale;
quadratic interpolation is usually quantitatively in error;
quartic interpolation appears to be the lowest order for
reliable quantitative accuracy.

The number of zero eigenvalues, \verb|nZeroEv|, indicates
the number of decoupled systems in this patch configuration.
\begin{matlab}
%}
  evals = eig(Jac);
  [~,k] = sort(abs(evals));
  evals=evals(k);
  nZeroEv = sum(abs(evals(:))<1e-5) 
  leadingEvals = evals(1:2*nPatch)
%{
\end{matlab}

\paragraph{Pseuso-spectrum of the Jacobian}
\begin{matlab}
%}
figure(1)
multiscalePseudoSpectra(Jac,1,1,200)
figfn=mfilename;
set(gcf,'PaperUnits','centimeters' ...
      ,'PaperPosition',[0 0 14 14] ...
      ,'renderer','Painters')
print('-depsc2',figfn)
matlab2tikz([figfn '.tex'],'showInfo',false ...
    ,'noSize',true,'parseStrings',false,'showWarnings',false ...
    ,'extraCode',['\tikzsetnextfilename{' figfn '}'] ...
    ,'extraAxisOptions','\extraAxisOptions' ...
    ,'checkForUpdates',false)
%{
\end{matlab}



%\input{../Patch/idealWavePDE.m}

%}
