% Computes elastic boundary conditions,
% but only for those patches that require boundary conditions.
% 
% 1-intX needs BC in X; intX needs interpolation in X
% 1-intY needs BC in Y; intY needs interpolation in Y
%
% JEB Jan 2024
% currently doesn't do anything---i.e., no BC
function u = heteroElasticBC2(u,patches)
    u([1 end],:,:,:,:,:) = ...
        reshape(1-patches.intX,[1 1 1 1 size(patches.intX)]) ...
        .*u([2 end-1],:,:,:,:,:) ...
        + reshape(patches.intX,[1 1 1 1 size(patches.intX)]) ...
        .*u([1 end],:,:,:,:,:);
    u(:,[1 end],:,:,:,:) = ...
        reshape(1-patches.intY,[1 1 1 1 size(patches.intY)]) ...
        .*u(:,[2 end-1],:,:,:,:) ...
        + reshape(patches.intY,[1 1 1 1 size(patches.intY)]) ...
        .*u(:,[1 end],:,:,:,:);
    % could NaN the following if want to
   % u(1,1,:,:,:,:)=NaN; % bottom left is irrelevant 
   % u(end,end,:,:,:,:)=NaN; % top right is irrelevant
   % u(1,end,[2 4],:,:,:)=NaN; % top left irrelvant for v
   % u(end,1,[1 3],:,:,:)=NaN; % bottom right irrelvant for u
end