% Computes no flux boundary conditions,
% but only for those patches that require boundary conditions.
% 
% 1-intX needs BC in X; intX needs interpolation in X
% 1-intY needs BC in Y; intY needs interpolation in Y
%
% JEB Dec 2023 

function u = heteroDiffBC2(u,patches)
    u([1 end],:,:,:,:,:) = ...
        reshape(1-patches.intX,[1 1 1 1 size(patches.intX)]) ...
        .*u([2 end-1],:,:,:,:,:) ...
        + reshape(patches.intX,[1 1 1 1 size(patches.intX)]) ...
        .*u([1 end],:,:,:,:,:);
    u(:,[1 end],:,:,:,:) = ...
        reshape(1-patches.intY,[1 1 1 1 size(patches.intY)]) ...
        .*u(:,[2 end-1],:,:,:,:) ...
        + reshape(patches.intY,[1 1 1 1 size(patches.intY)]) ...
        .*u(:,[1 end],:,:,:,:);
    u([1 end],[1 end],:,:,:,:)=NaN; % corners are irrelevant
end


